version: 2.1
jobs:
  build:
    docker:
      - image: docker.pkg.github.com/graalvm/container/community:latest
        auth:
          username: dsantibanezvera
          password: Z5x0w|$G
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-dependencies-native
      - run:
          name: native-image
          command: |
            ./gradlew build -Dquarkus.package.type=native --debug
      - run:
          name: print-test-report
          command: |
            cat /root/project/build/reports/tests/test/index.html
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-native
      - store_artifacts:
          path: build/libs
      - store_artifacts:
          path: build/graal